image: gitpod/workspace-dotnet

ports:
  - port: 8080
    onOpen: open-preview

tasks:
   # runs during prebuild
  - init: yarn && gp sync-done yarn
  - command: gp sync-await yarn && yarn dev:start
  - command: gp await-port 8080 && yarn fsharp:dev


vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
    - Ionide.Ionide-fsharp@4.6.2:yBkAE6j7z7gJ5WEcyMjEOg==
