image: gitpod/workspace-dotnet:branch-jesterornot-fsharp-interactive-193@sha256:8773b78d41b29053ec8b08dc70562a1e8ea351fbd863fe9a3175b7f3ee6521f4

ports:
  - port: 8080
    onOpen: open-preview

tasks:
   # runs during prebuild
  - init: yarn && gp sync-done yarn
  - command: gp sync-await yarn && yarn dev:start
  - command: gp await-port 8080 && yarn fsharp:dev


vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
    - Ionide.Ionide-fsharp@4.6.2:yBkAE6j7z7gJ5WEcyMjEOg==
